# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
        - main

        pool:
          vmImage: 'ubuntu-latest' # set to windows-latest or another Windows vmImage for Windows builds
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

        variables:
          imageName: 'pipelines-javascript-docker'

        steps:
        - task: Docker@2
          displayName: Build an image
          inputs:deepa99
            repository: 
            command: build
            Dockerfile: app/Dockerfile
